// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


CloudTemperature temperature;
CloudInt moisture;
CloudInt light;
CloudInt conductivity;
CloudInt battery;

void initProperties(){

  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(moisture, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(light, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(conductivity, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(battery, READ, ON_CHANGE, NULL, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
